
num_rotors: 4

# ros2 backend
stage_prefix: quadrotor
usd_file: 
rotor_constant:
- 8.54858e-6
- 8.54858e-6
- 8.54858e-6
- 8.54858e-6
rolling_moment_coefficient:
- 1.0e-6
- 1.0e-6
- 1.0e-6
- 1.0e-6
rot_dir:
- -1.0
- -1.0
- 1.0
- 1.0
min_rotor_velocity:
- 0.0
- 0.0
- 0.0
- 0.0
max_rotor_velocity:
- 1100.0
- 1100.0
- 1100.0
- 1100.0
drag:
- 0.50
- 0.30
- 0.00
use_barometer: true
use_imu: true
use_magnetometer: true
use_gps: true

# px4 backend
connection_type: tcpin
connection_ip: 127.0.0.1
connection_baseport: 25560
enable_lockstep: true
px4_autolaunch: true
px4_dir: /home/fei/PX4-Autopilot
px4_vehicle_model: gazebo-classic_iris
input_offset:
- 0.0
- 0.0
- 0.0
- 0.0
input_scaling:
- 1000.0
- 1000.0
- 1000.0
- 1000.0
zero_position_armed:
- 100.0
- 100.0
- 100.0
- 100.0
update_rate: 250.0
send_ground_truth: false
