
num_rotors: 4

# vehicle config
stage_prefix: quadrotor
usd_file: 
rotor_constant:
- 8.54858e-6
- 8.54858e-6
- 8.54858e-6
- 8.54858e-6
rolling_moment_coefficient:
- 1.0e-6
- 1.0e-6
- 1.0e-6
- 1.0e-6
rot_dir:
- -1.0
- -1.0
- 1.0
- 1.0
min_rotor_velocity:
- 0.0
- 0.0
- 0.0
- 0.0
max_rotor_velocity:
- 1100.0
- 1100.0
- 1100.0
- 1100.0
drag:
- 0.50
- 0.30
- 0.00
use_barometer: true
use_imu: true
use_magnetometer: true
use_gps: true

prop_C_T : 0.1        # 推力系数 C_T
prop_C_Q : 0.01       # 扭矩系数 C_Q
prop_diameter : 0.203 # 螺旋桨直径 D (m, 8英寸)
air_density : 1.225   # 空气密度 rho (kg/m^3)

kv : 1000
resistance_motor : 0.05 # R_motor (Ohm)
io_current : 0.4        # I_o (A)
esc_efficiency : 0.95
battery_v_full : 16.8   # 4S 满电电压 (V)
resistance_internal : 0.03 # R_internal (Ohm)
base_power_electronics : 5.0 # 基础电子功耗 (W)

#lidar_config
lidar_list:
- lidar_name: lidar_01
  lidar_config:
    frequency: 10.0
    sensor_configuration: OS1_REV6_32ch10hz2048res
    position:
    - 0.1
    - -0.05
    - 0.1
    orientation:
    - 0.0
    - 0.0
    - 0.0
    show_render: True
# - lidar_name: lidar_02
#   lidar_config:
#     frequency: 10.0
#     sensor_configuration: OS1_REV6_32ch10hz2048res
#     position:
#     - 0.0
#     - 0.0
#     - 0.5
#     orientation:
#     - 0.0
#     - 0.0
#     - 0.0
#     show_render: True

#camera_config
camera_list:
- camera_name: camera_01
  camera_config:
    depth: false
    position: 
    - 0.1
    - 0.05
    - 0.06
    orientation: 
    - 0.0
    - 0.0
    - 180.0
    frequency: 30
- camera_name: camera_02
  camera_config:
    depth: false
    position: 
    - 0.0
    - 0.0
    - -0.07
    orientation: 
    - 0.0
    - -90.0
    - 180.0
    frequency: 30

# ros2 backend config
accel_topic: state/accel
gps_topic: sensors/gps
gps_vel_topic: sensors/gps_vel
imu_topic: sensors/imu
mag_topic: sensors/mag
namespace: vehicle
pose_topic: state/pose
pub_accel: true
pub_gps: true
pub_gps_vel: true
pub_graphical_sensors: true
pub_imu: true
pub_mag: true
pub_pose: true
pub_sensors: true
pub_state: true
pub_tf: false
pub_twist: true
pub_twist_inertial: true
sub_control: true
twist_inertial_topic: state/twist_inertial
twist_topic: state/twist

# px4 backend config
connection_type: tcpin
connection_ip: 127.0.0.1
connection_baseport: 25560
enable_lockstep: true
px4_autolaunch: true
px4_dir: /home/fei/PX4-Autopilot
px4_vehicle_model: gazebo-classic_iris
input_offset:
- 0.0
- 0.0
- 0.0
- 0.0
input_scaling:
- 1000.0
- 1000.0
- 1000.0
- 1000.0
zero_position_armed:
- 100.0
- 100.0
- 100.0
- 100.0
update_rate: 250.0
send_ground_truth: false
